---
    name: CI/CD
    
    on:
      push:
        branches: 
          - master
    jobs:
      # build:
      #   runs-on: ubuntu-latest
      #   steps:
      #     - name: Checkout source 
      #       uses: actions/checkout@v3
    
      #     - name: Login to DockerHub
      #       uses: docker/login-action@v2
      #       with:
      #         username: ${{ secrets.DOCKERHUB_USERNAME }}
      #         password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     - name: build and push to DockerHub
      #       run: |
      #         docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
      #         docker buildx inspect --bootstrap
      #         docker buildx build --platform linux/amd64,linux/arm64/v8 --push --tag aman7681/todo:latest .
        
    
      deploy:
        # needs: build
        runs-on: [ec2-user]
        steps: 
          - name: Login to DockerHub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Pull image from docker hub
            run: docker pull aman7681/todo:latest
          - name: Delete old container
            run: docker rm -f todo-container
          - name: Run docker container
            run: docker run -d -p 8080:8080 --name todo-container aman7681/todo 
          # - name: Run forground process
          #   run: docker run -d aman7681/todo:latest tail -f /dev/null
          - name: Show containers
            run: docker ps
    
    
